name: sunbible
summary: A simply beautiful place to read, study, and memorize the Bible.
description: |
  A simply beautiful place to read, study, and memorize the Bible. Feauturing the beautiful language of the KJV.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

apps:
  sunbible:
    command: desktop-launch $SNAP/sunbible/SunBible

parts:
  sunbible:
    plugin: nodejs
    node-engine: 18.15.0
    source-type: git
    source: https://github.com/SunBible-dev/SunBible.git
        
    build:
      - yarn install && yarn snap