name: Snap Release Workflow

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: yarn install
      - name: Build app for Snap
        run: yarn snap
      - name: Build app for Snap Arm
        run: yarn snaparm
      - name: Upload Dist
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist/